[package]
name = "sysfetch"
version = "0.0.0"
authors = ["Jacob Hrbek"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nameof = "1.2.1"
curl = "0.4.34"