[package]
name = "sysfetch"
description = "FIXME-DOCS"
keywods = "FIXME-DOCS"
version = "0.0.0"
authors = ["Jacob Hrbek"]
edition = "2018"

[features]
default = "TBD"

[dependencies]
# To provide a standard paths for cross-platform development
directories-next = "2.0.0"